//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int Id { get; set; }
        public int ProgramId { get; set; }
        public int DurationId { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<double> TotalFees { get; set; }
        public Nullable<double> AdvanceFees { get; set; }
    
        public virtual DurationType DurationType { get; set; }
        public virtual Program Program { get; set; }
    }
}
